// nuxt-resend-examples/javascript/pages/prevent-threading.vue
<script setup>
const to = ref("delivered@resend.dev");
const subject = ref("Order Confirmation");
const count = ref(3);
const loading = ref(false);
const success = ref(null);
const error = ref(null);

async function sendEmails() {
  loading.value = true;
  success.value = null;
  error.value = null;

  const results = [];

  try {
    for (let i = 1; i <= count.value; i++) {
      const data = await $fetch("/api/send", {
        method: "POST",
        body: {
          to: to.value,
          subject: subject.value,
          message: `This is email #${i} -- each appears as a separate conversation in Gmail.`,
        },
      });
      results.push(`Email #${i} sent: ${data.id}`);
    }
    success.value =
      results.join("\n") +
      "\n\nAll emails sent with unique X-Entity-Ref-ID headers.\nEach will appear as a separate conversation in Gmail.";
  } catch (err) {
    error.value = err.data?.message || err.message || "Failed to send emails";
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div>
    <PageHeader
      title="Prevent Threading"
      description="Send emails with unique X-Entity-Ref-ID headers so Gmail treats each as a separate conversation."
    />

    <form class="form" @submit.prevent="sendEmails">
      <div class="field">
        <label for="to">To</label>
        <input id="to" v-model="to" type="email" required />
      </div>
      <div class="field">
        <label for="subject">Subject (same for all)</label>
        <input id="subject" v-model="subject" type="text" required />
      </div>
      <div class="field">
        <label for="count">Number of Emails</label>
        <input id="count" v-model.number="count" type="number" min="1" max="10" required />
      </div>
      <button type="submit" :disabled="loading">
        {{ loading ? "Sending..." : "Send Emails" }}
      </button>
    </form>

    <ResultDisplay :loading="loading" :success="success" :error="error" />

    <div class="code-example">
      <h3>Code Example</h3>
      <pre><code>// Gmail groups emails by subject and Message-ID/References headers.
// Adding a unique X-Entity-Ref-ID header prevents this grouping.
const { data, error } = await resend.emails.send({
  from: config.emailFrom,
  to: [to],
  subject: "Order Confirmation",
  html: "&lt;p&gt;This is a separate conversation&lt;/p&gt;",
  headers: {
    "X-Entity-Ref-ID": crypto.randomUUID(),
  },
});</code></pre>
    </div>
  </div>
</template>

<style scoped>
.form {
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.field label {
  font-size: 0.875rem;
  font-weight: 500;
}

.field input {
  padding: 0.5rem 0.75rem;
  border: 1px solid #d4d4d8;
  border-radius: 6px;
  font-size: 0.875rem;
}

button {
  padding: 0.625rem 1.25rem;
  background: #18181b;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  align-self: flex-start;
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.code-example {
  margin-top: 2rem;
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
}

.code-example h3 {
  font-size: 1rem;
  margin-bottom: 1rem;
}

.code-example pre {
  background: #f4f4f5;
  padding: 1rem;
  border-radius: 6px;
  overflow-x: auto;
  font-size: 0.8rem;
  line-height: 1.5;
}
</style>

// remix-resend-examples/typescript/app/routes/prevent-threading.tsx
import { useFetcher } from "@remix-run/react";
import type { ActionFunctionArgs, MetaFunction } from "@remix-run/node";
import { json } from "@remix-run/node";
import { Resend } from "resend";
import { PageHeader } from "~/components/PageHeader";
import { ResultDisplay } from "~/components/ResultDisplay";

const resend = new Resend(process.env.RESEND_API_KEY);

export const meta: MetaFunction = () => {
  return [{ title: "Prevent Threading - Remix + Resend" }];
};

export async function action({ request }: ActionFunctionArgs) {
  const formData = await request.formData();
  const to = formData.get("to") as string;
  const subject = formData.get("subject") as string;
  const message = formData.get("message") as string;

  if (!to || !subject || !message) {
    return json(
      { error: "Missing required fields: to, subject, message" },
      { status: 400 }
    );
  }

  const from = process.env.EMAIL_FROM || "Acme <onboarding@resend.dev>";

  // Adding a unique X-Entity-Ref-ID header prevents Gmail from
  // grouping emails with the same subject into a single thread.
  const { data, error } = await resend.emails.send({
    from,
    to: [to],
    subject,
    html: `<h1>${subject}</h1><p>${message}</p>`,
    headers: {
      "X-Entity-Ref-ID": crypto.randomUUID(),
    },
  });

  if (error) {
    return json({ error: error.message }, { status: 500 });
  }

  return json({ success: true, id: data?.id });
}

export default function PreventThreading() {
  const fetcher = useFetcher<typeof action>();

  return (
    <div>
      <PageHeader
        title="Prevent Threading"
        description="Send emails with a unique X-Entity-Ref-ID header so Gmail treats each as a separate conversation."
      />

      <fetcher.Form method="post" style={{ display: "grid", gap: "16px" }}>
        <div>
          <label htmlFor="to" style={labelStyle}>
            To
          </label>
          <input
            id="to"
            name="to"
            type="email"
            placeholder="delivered@resend.dev"
            required
            style={inputStyle}
          />
        </div>
        <div>
          <label htmlFor="subject" style={labelStyle}>
            Subject
          </label>
          <input
            id="subject"
            name="subject"
            defaultValue="Order Confirmation"
            required
            style={inputStyle}
          />
        </div>
        <div>
          <label htmlFor="message" style={labelStyle}>
            Message
          </label>
          <textarea
            id="message"
            name="message"
            defaultValue="This email will appear as a separate conversation in Gmail."
            required
            rows={3}
            style={inputStyle}
          />
        </div>
        <button type="submit" style={buttonStyle}>
          {fetcher.state === "submitting" ? "Sending..." : "Send (No Threading)"}
        </button>
      </fetcher.Form>

      <ResultDisplay state={fetcher.state} data={fetcher.data} />

      <div style={codeBlockStyle}>
        <h3 style={{ margin: "0 0 12px 0", fontSize: "14px" }}>API Code</h3>
        <pre style={preStyle}>{`const { data, error } = await resend.emails.send({
  from: "Acme <onboarding@resend.dev>",
  to: ["delivered@resend.dev"],
  subject: "Order Confirmation",
  html: "<h1>Order Confirmation</h1><p>Details...</p>",
  headers: {
    "X-Entity-Ref-ID": crypto.randomUUID(),
  },
});`}</pre>
      </div>
    </div>
  );
}

const labelStyle: React.CSSProperties = {
  display: "block",
  marginBottom: "4px",
  fontSize: "14px",
  fontWeight: 500,
};

const inputStyle: React.CSSProperties = {
  width: "100%",
  padding: "8px 12px",
  border: "1px solid #d4d4d8",
  borderRadius: "6px",
  fontSize: "14px",
  boxSizing: "border-box",
};

const buttonStyle: React.CSSProperties = {
  padding: "10px 20px",
  backgroundColor: "#18181b",
  color: "#fff",
  border: "none",
  borderRadius: "6px",
  fontSize: "14px",
  fontWeight: 500,
  cursor: "pointer",
};

const codeBlockStyle: React.CSSProperties = {
  marginTop: "32px",
  padding: "20px",
  backgroundColor: "#18181b",
  borderRadius: "8px",
  color: "#e4e4e7",
};

const preStyle: React.CSSProperties = {
  margin: 0,
  fontSize: "13px",
  whiteSpace: "pre-wrap",
  wordBreak: "break-all",
};
