// redwoodjs-resend-examples/javascript/web/src/components/PageHeader.jsx
import { Link } from "@redwoodjs/router";

export function PageHeader({ title, description }) {
  return (
    <div style={{ marginBottom: "32px" }}>
      <Link
        to="/"
        style={{
          color: "#71717a",
          textDecoration: "none",
          fontSize: "14px",
          display: "inline-block",
          marginBottom: "16px",
        }}
      >
        &larr; Back to examples
      </Link>
      <h1 style={{ margin: "0 0 8px 0", fontSize: "28px" }}>{title}</h1>
      <p style={{ margin: 0, color: "#71717a", fontSize: "16px" }}>
        {description}
      </p>
    </div>
  );
}

// sveltekit-resend-examples/javascript/src/lib/components/PageHeader.svelte
<script>
  let { title, description } = $props();
</script>

<div class="page-header">
  <a href="/" class="back-link">&larr; Back to examples</a>
  <h1>{title}</h1>
  <p class="description">{description}</p>
</div>

<style>
  .page-header {
    margin-bottom: 2rem;
  }

  .back-link {
    display: inline-block;
    margin-bottom: 1rem;
    color: #6366f1;
    text-decoration: none;
    font-size: 0.875rem;
  }

  .back-link:hover {
    text-decoration: underline;
  }

  h1 {
    font-size: 1.875rem;
    font-weight: 700;
    color: #111827;
    margin: 0 0 0.5rem;
  }

  .description {
    color: #6b7280;
    margin: 0;
    font-size: 1rem;
  }
</style>
