// nuxt-resend-examples/javascript/components/ResultDisplay.vue
<script setup>
defineProps({
  loading: {
    type: Boolean,
    default: false,
  },
  success: {
    type: String,
    default: null,
  },
  error: {
    type: String,
    default: null,
  },
});
</script>

<template>
  <div class="result-display">
    <div v-if="loading" class="result loading">Sending...</div>
    <div v-if="success" class="result success">{{ success }}</div>
    <div v-if="error" class="result error">{{ error }}</div>
  </div>
</template>

<style scoped>
.result {
  margin-top: 1rem;
  padding: 1rem;
  border-radius: 6px;
  font-size: 0.875rem;
}

.result.loading {
  background: #eff6ff;
  color: #1d4ed8;
  border: 1px solid #bfdbfe;
}

.result.success {
  background: #f0fdf4;
  color: #166534;
  border: 1px solid #bbf7d0;
  white-space: pre-wrap;
}

.result.error {
  background: #fef2f2;
  color: #991b1b;
  border: 1px solid #fecaca;
}
</style>

// sveltekit-resend-examples/javascript/src/lib/components/ResultDisplay.svelte
<script>
  let { loading, error, success, data = null } = $props();
</script>

{#if loading}
  <div class="result loading">
    <p>Sending...</p>
  </div>
{/if}

{#if error}
  <div class="result error">
    <p class="label">Error</p>
    <p>{error}</p>
  </div>
{/if}

{#if success}
  <div class="result success">
    <p class="label">Success</p>
    <p>{success}</p>
    {#if data}
      <pre>{JSON.stringify(data, null, 2)}</pre>
    {/if}
  </div>
{/if}

<style>
  .result {
    margin-top: 1.5rem;
    padding: 1rem;
    border-radius: 0.5rem;
    border: 1px solid;
  }

  .loading {
    border-color: #d1d5db;
    background-color: #f9fafb;
    color: #374151;
  }

  .error {
    border-color: #fca5a5;
    background-color: #fef2f2;
    color: #991b1b;
  }

  .success {
    border-color: #86efac;
    background-color: #f0fdf4;
    color: #166534;
  }

  .label {
    font-weight: 600;
    margin: 0 0 0.25rem;
  }

  pre {
    margin-top: 0.75rem;
    padding: 0.75rem;
    background-color: rgba(0, 0, 0, 0.05);
    border-radius: 0.375rem;
    font-size: 0.75rem;
    overflow-x: auto;
    white-space: pre-wrap;
    word-break: break-all;
  }
</style>
