// sveltekit-resend-examples/typescript/src/routes/double-optin/+page.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import PageHeader from "$lib/components/PageHeader.svelte";
  import ResultDisplay from "$lib/components/ResultDisplay.svelte";

  let email = $state("");
  let loading = $state(false);
  let error = $state<string | null>(null);
  let success = $state<string | null>(null);
  let data = $state<unknown>(null);

  let confirmed = $derived($page.url.searchParams.get("confirmed") === "true");

  async function handleSubscribe() {
    loading = true;
    error = null;
    success = null;
    data = null;

    try {
      const response = await fetch("/api/double-optin/subscribe", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email }),
      });

      const result = await response.json();

      if (!response.ok) {
        error = result.error || "Failed to subscribe";
        return;
      }

      success = "Confirmation email sent! Check your inbox.";
      data = result;
    } catch (err) {
      error = err instanceof Error ? err.message : "An error occurred";
    } finally {
      loading = false;
    }
  }
</script>

<PageHeader
  title="Double Opt-in"
  description="Implement a subscription flow with email confirmation."
/>

{#if confirmed}
  <div class="confirmed">
    <h2>Subscription Confirmed!</h2>
    <p>Your email has been verified and you are now subscribed.</p>
  </div>
{/if}

<form onsubmit={handleSubscribe} class="form">
  <div class="field">
    <label for="email">Email Address</label>
    <input id="email" type="email" bind:value={email} placeholder="you@example.com" required />
  </div>

  <button type="submit" disabled={loading}>
    {loading ? "Subscribing..." : "Subscribe"}
  </button>
</form>

<ResultDisplay {loading} {error} {success} {data} />

<details class="code-example">
  <summary>View example code</summary>
  <pre><code>{`// src/routes/api/double-optin/subscribe/+server.ts
import { json } from '@sveltejs/kit';
import { resend } from '$lib/server/resend';
import {
  EMAIL_FROM,
  RESEND_AUDIENCE_ID,
  CONFIRM_REDIRECT_URL,
} from '$env/static/private';
import type { RequestHandler } from './$types';

export const POST: RequestHandler = async ({ request }) => {
  const { email } = await request.json();

  // Add unsubscribed contact to audience
  const { error: contactError } = await resend.contacts.create({
    audienceId: RESEND_AUDIENCE_ID,
    email,
    unsubscribed: true,
  });

  if (contactError) {
    return json({ error: contactError.message }, { status: 400 });
  }

  // Send confirmation email
  const confirmUrl = \`\${CONFIRM_REDIRECT_URL}&email=\${encodeURIComponent(email)}\`;

  const { data, error } = await resend.emails.send({
    from: EMAIL_FROM,
    to: [email],
    subject: 'Confirm your subscription',
    html: \`
      <h1>Confirm your subscription</h1>
      <p>Click the link below to confirm your email address:</p>
      <a href="\${confirmUrl}">Confirm Subscription</a>
    \`,
  });

  if (error) {
    return json({ error: error.message }, { status: 400 });
  }

  return json(data);
};

// src/routes/api/double-optin/confirm/+server.ts
// POST: Update contact to subscribed
export const POST: RequestHandler = async ({ request }) => {
  const { email } = await request.json();

  const { data, error } = await resend.contacts.update({
    audienceId: RESEND_AUDIENCE_ID,
    email,
    unsubscribed: false,
  });

  if (error) {
    return json({ error: error.message }, { status: 400 });
  }

  return json(data);
};`}</code></pre>
</details>

<style>
  .confirmed {
    padding: 1.5rem;
    background: #f0fdf4;
    border: 1px solid #86efac;
    border-radius: 0.5rem;
    margin-bottom: 2rem;
  }

  .confirmed h2 {
    color: #166534;
    margin: 0 0 0.5rem;
    font-size: 1.25rem;
  }

  .confirmed p {
    color: #15803d;
    margin: 0;
  }

  .form {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    max-width: 32rem;
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }

  label {
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
  }

  input {
    padding: 0.5rem 0.75rem;
    border: 1px solid #d1d5db;
    border-radius: 0.375rem;
    font-size: 0.875rem;
  }

  input:focus {
    outline: none;
    border-color: #6366f1;
    box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
  }

  button {
    align-self: flex-start;
    padding: 0.5rem 1.25rem;
    background-color: #6366f1;
    color: #ffffff;
    border: none;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
  }

  button:hover:not(:disabled) {
    background-color: #4f46e5;
  }

  button:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .code-example {
    margin-top: 2rem;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
    overflow: hidden;
  }

  summary {
    padding: 0.75rem 1rem;
    background: #f9fafb;
    cursor: pointer;
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
  }

  pre {
    margin: 0;
    padding: 1rem;
    background: #1f2937;
    color: #e5e7eb;
    font-size: 0.8rem;
    overflow-x: auto;
  }
</style>

// nuxt-resend-examples/javascript/pages/double-optin.vue
<script setup>
const email = ref("");
const name = ref("");
const loading = ref(false);
const success = ref(null);
const error = ref(null);

async function subscribe() {
  loading.value = true;
  success.value = null;
  error.value = null;

  try {
    const data = await $fetch("/api/send", {
      method: "POST",
      body: {
        to: email.value,
        subject: "Confirm your subscription",
        message: `${name.value ? `Welcome, ${name.value}!` : "Welcome!"} Please confirm your subscription by clicking the link in this email.`,
      },
    });
    success.value = `Confirmation email sent!\nEmail ID: ${data.id}\n\nNext steps:\n1. User clicks the confirmation link in the email\n2. Resend fires an 'email.clicked' webhook event\n3. Your webhook handler updates the contact to unsubscribed=false`;
  } catch (err) {
    error.value = err.data?.message || err.message || "Failed to subscribe";
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div>
    <PageHeader
      title="Double Opt-in"
      description="Implement a double opt-in subscription flow with Resend."
    />

    <form class="form" @submit.prevent="subscribe">
      <div class="field">
        <label for="email">Email</label>
        <input id="email" v-model="email" type="email" placeholder="user@example.com" required />
      </div>
      <div class="field">
        <label for="name">Name (optional)</label>
        <input id="name" v-model="name" type="text" placeholder="Jane Doe" />
      </div>
      <button type="submit" :disabled="loading">
        {{ loading ? "Subscribing..." : "Subscribe" }}
      </button>
    </form>

    <ResultDisplay :loading="loading" :success="success" :error="error" />

    <div class="info-section">
      <h3>How Double Opt-in Works</h3>
      <ol>
        <li>User submits their email address</li>
        <li>Create contact with <code>unsubscribed: true</code> (pending confirmation)</li>
        <li>Send a confirmation email with a link</li>
        <li>User clicks the confirmation link</li>
        <li>Resend fires an <code>email.clicked</code> webhook event</li>
        <li>Webhook handler updates the contact to <code>unsubscribed: false</code></li>
      </ol>
    </div>

    <div class="code-example">
      <h3>Code Example</h3>
      <pre><code>// Step 1: Create contact (pending)
const { data: contact } = await resend.contacts.create({
  audienceId,
  email,
  firstName: name,
  unsubscribed: true, // pending confirmation
});

// Step 2: Send confirmation email
const { data: sent } = await resend.emails.send({
  from: config.emailFrom,
  to: [email],
  subject: "Confirm your subscription",
  html: confirmationHtml,
});

// Step 3: In webhook handler (email.clicked event)
await resend.contacts.update({
  audienceId,
  id: contact.id,
  unsubscribed: false, // confirmed!
});</code></pre>
    </div>
  </div>
</template>

<style scoped>
.form {
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.field label {
  font-size: 0.875rem;
  font-weight: 500;
}

.field input {
  padding: 0.5rem 0.75rem;
  border: 1px solid #d4d4d8;
  border-radius: 6px;
  font-size: 0.875rem;
}

button {
  padding: 0.625rem 1.25rem;
  background: #18181b;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  align-self: flex-start;
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.info-section {
  margin-top: 2rem;
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
}

.info-section h3 {
  font-size: 1rem;
  margin-bottom: 1rem;
}

.info-section ol {
  padding-left: 1.25rem;
  font-size: 0.875rem;
  line-height: 1.8;
}

.info-section code {
  background: #f4f4f5;
  padding: 0.125rem 0.375rem;
  border-radius: 3px;
  font-size: 0.8rem;
}

.code-example {
  margin-top: 2rem;
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
}

.code-example h3 {
  font-size: 1rem;
  margin-bottom: 1rem;
}

.code-example pre {
  background: #f4f4f5;
  padding: 1rem;
  border-radius: 6px;
  overflow-x: auto;
  font-size: 0.8rem;
  line-height: 1.5;
}
</style>
