// remix-resend-examples/javascript/app/routes/double-optin.jsx
import { useFetcher } from "@remix-run/react";
import { json } from "@remix-run/node";
import { Resend } from "resend";
import { PageHeader } from "~/components/PageHeader";
import { ResultDisplay } from "~/components/ResultDisplay";

const resend = new Resend(process.env.RESEND_API_KEY);

export const meta = () => {
  return [{ title: "Double Opt-in - Remix + Resend" }];
};

export async function action({ request }) {
  const formData = await request.formData();
  const email = formData.get("email");
  const name = formData.get("name");

  if (!email) {
    return json({ error: "Missing required field: email" }, { status: 400 });
  }

  const segmentId = process.env.RESEND_SEGMENT_ID;
  if (!segmentId) {
    return json({ error: "RESEND_SEGMENT_ID not configured" }, { status: 500 });
  }

  const confirmUrl =
    process.env.CONFIRM_REDIRECT_URL || "https://example.com/confirmed";
  const from = process.env.EMAIL_FROM || "Acme <onboarding@resend.dev>";

  const { data: contact, error: contactError } = await resend.contacts.create({
    email,
    firstName: name || undefined,
    unsubscribed: true,
    segments: [{ id: segmentId }],
  });

  if (contactError) {
    return json({ error: contactError.message }, { status: 500 });
  }

  const greeting = name ? `Welcome, ${name}!` : "Welcome!";
  const html = `<div style="text-align: center; padding: 40px 20px; font-family: Arial, sans-serif;">
  <h1>${greeting}</h1>
  <p>Please confirm your subscription to our newsletter.</p>
  <a href="${confirmUrl}" style="background-color: #18181b; color: #fff; padding: 12px 32px; border-radius: 6px; text-decoration: none; font-weight: bold; display: inline-block;">Confirm Subscription</a>
</div>`;

  const { data: sent, error: sendError } = await resend.emails.send({
    from,
    to: [email],
    subject: "Confirm your subscription",
    html,
  });

  if (sendError) {
    return json({ error: sendError.message }, { status: 500 });
  }

  return json({
    success: true,
    message: "Confirmation email sent",
    contact_id: contact?.id,
    email_id: sent?.id,
  });
}

export default function DoubleOptin() {
  const fetcher = useFetcher();

  return (
    <div>
      <PageHeader
        title="Double Opt-in"
        description="Implement a double opt-in subscription flow. The contact is created as unsubscribed, then confirmed via a webhook when they click the link."
      />

      <fetcher.Form method="post" style={{ display: "grid", gap: "16px" }}>
        <div>
          <label htmlFor="email" style={labelStyle}>
            Email
          </label>
          <input
            id="email"
            name="email"
            type="email"
            placeholder="jane@example.com"
            required
            style={inputStyle}
          />
        </div>
        <div>
          <label htmlFor="name" style={labelStyle}>
            Name (optional)
          </label>
          <input
            id="name"
            name="name"
            placeholder="Jane Doe"
            style={inputStyle}
          />
        </div>
        <button type="submit" style={buttonStyle}>
          {fetcher.state === "submitting" ? "Subscribing..." : "Subscribe"}
        </button>
      </fetcher.Form>

      <ResultDisplay state={fetcher.state} data={fetcher.data} />

      <div style={codeBlockStyle}>
        <h3 style={{ margin: "0 0 12px 0", fontSize: "14px" }}>How it works</h3>
        <pre style={preStyle}>{`// 1. Create contact as unsubscribed
const { data: contact } = await resend.contacts.create({
  email,
  firstName: name,
  unsubscribed: true,
  segments: [{ id: segmentId }],
});

// 2. Send confirmation email with a link
await resend.emails.send({
  from,
  to: [email],
  subject: "Confirm your subscription",
  html: '<a href="...">Confirm Subscription</a>',
});

// 3. In webhook handler (email.clicked event):
await resend.contacts.update({
  id: contact.id,
  unsubscribed: false,
});`}</pre>
      </div>
    </div>
  );
}

const labelStyle = {
  display: "block",
  marginBottom: "4px",
  fontSize: "14px",
  fontWeight: 500,
};

const inputStyle = {
  width: "100%",
  padding: "8px 12px",
  border: "1px solid #d4d4d8",
  borderRadius: "6px",
  fontSize: "14px",
  boxSizing: "border-box",
};

const buttonStyle = {
  padding: "10px 20px",
  backgroundColor: "#18181b",
  color: "#fff",
  border: "none",
  borderRadius: "6px",
  fontSize: "14px",
  fontWeight: 500,
  cursor: "pointer",
};

const codeBlockStyle = {
  marginTop: "32px",
  padding: "20px",
  backgroundColor: "#18181b",
  borderRadius: "8px",
  color: "#e4e4e7",
};

const preStyle = {
  margin: 0,
  fontSize: "13px",
  whiteSpace: "pre-wrap",
  wordBreak: "break-all",
};

// nuxt-resend-examples/javascript/pages/double-optin.vue
<script setup>
const email = ref("");
const name = ref("");
const loading = ref(false);
const success = ref(null);
const error = ref(null);

async function subscribe() {
  loading.value = true;
  success.value = null;
  error.value = null;

  try {
    const data = await $fetch("/api/send", {
      method: "POST",
      body: {
        to: email.value,
        subject: "Confirm your subscription",
        message: `${name.value ? `Welcome, ${name.value}!` : "Welcome!"} Please confirm your subscription by clicking the link in this email.`,
      },
    });
    success.value = `Confirmation email sent!\nEmail ID: ${data.id}\n\nNext steps:\n1. User clicks the confirmation link in the email\n2. Resend fires an 'email.clicked' webhook event\n3. Your webhook handler updates the contact to unsubscribed=false`;
  } catch (err) {
    error.value = err.data?.message || err.message || "Failed to subscribe";
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div>
    <PageHeader
      title="Double Opt-in"
      description="Implement a double opt-in subscription flow with Resend."
    />

    <form class="form" @submit.prevent="subscribe">
      <div class="field">
        <label for="email">Email</label>
        <input id="email" v-model="email" type="email" placeholder="user@example.com" required />
      </div>
      <div class="field">
        <label for="name">Name (optional)</label>
        <input id="name" v-model="name" type="text" placeholder="Jane Doe" />
      </div>
      <button type="submit" :disabled="loading">
        {{ loading ? "Subscribing..." : "Subscribe" }}
      </button>
    </form>

    <ResultDisplay :loading="loading" :success="success" :error="error" />

    <div class="info-section">
      <h3>How Double Opt-in Works</h3>
      <ol>
        <li>User submits their email address</li>
        <li>Create contact with <code>unsubscribed: true</code> (pending confirmation)</li>
        <li>Send a confirmation email with a link</li>
        <li>User clicks the confirmation link</li>
        <li>Resend fires an <code>email.clicked</code> webhook event</li>
        <li>Webhook handler updates the contact to <code>unsubscribed: false</code></li>
      </ol>
    </div>

    <div class="code-example">
      <h3>Code Example</h3>
      <pre><code>// Step 1: Create contact (pending)
const { data: contact } = await resend.contacts.create({
  email,
  firstName: name,
  unsubscribed: true, // pending confirmation
  segments: [{ id: segmentId }],
});

// Step 2: Send confirmation email
const { data: sent } = await resend.emails.send({
  from: config.emailFrom,
  to: [email],
  subject: "Confirm your subscription",
  html: confirmationHtml,
});

// Step 3: In webhook handler (email.clicked event)
await resend.contacts.update({
  id: contact.id,
  unsubscribed: false, // confirmed!
});</code></pre>
    </div>
  </div>
</template>

<style scoped>
.form {
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.field label {
  font-size: 0.875rem;
  font-weight: 500;
}

.field input {
  padding: 0.5rem 0.75rem;
  border: 1px solid #d4d4d8;
  border-radius: 6px;
  font-size: 0.875rem;
}

button {
  padding: 0.625rem 1.25rem;
  background: #18181b;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  align-self: flex-start;
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.info-section {
  margin-top: 2rem;
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
}

.info-section h3 {
  font-size: 1rem;
  margin-bottom: 1rem;
}

.info-section ol {
  padding-left: 1.25rem;
  font-size: 0.875rem;
  line-height: 1.8;
}

.info-section code {
  background: #f4f4f5;
  padding: 0.125rem 0.375rem;
  border-radius: 3px;
  font-size: 0.8rem;
}

.code-example {
  margin-top: 2rem;
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
}

.code-example h3 {
  font-size: 1rem;
  margin-bottom: 1rem;
}

.code-example pre {
  background: #f4f4f5;
  padding: 1rem;
  border-radius: 6px;
  overflow-x: auto;
  font-size: 0.8rem;
  line-height: 1.5;
}
</style>
