// sveltekit-resend-examples/javascript/src/lib/components/PageHeader.svelte
<script>
  let { title, description } = $props();
</script>

<div class="page-header">
  <a href="/" class="back-link">&larr; Back to examples</a>
  <h1>{title}</h1>
  <p class="description">{description}</p>
</div>

<style>
  .page-header {
    margin-bottom: 2rem;
  }

  .back-link {
    display: inline-block;
    margin-bottom: 1rem;
    color: #6366f1;
    text-decoration: none;
    font-size: 0.875rem;
  }

  .back-link:hover {
    text-decoration: underline;
  }

  h1 {
    font-size: 1.875rem;
    font-weight: 700;
    color: #111827;
    margin: 0 0 0.5rem;
  }

  .description {
    color: #6b7280;
    margin: 0;
    font-size: 1rem;
  }
</style>

// nuxt-resend-examples/typescript/components/PageHeader.vue
<script setup lang="ts">
defineProps<{
  title: string;
  description: string;
}>();
</script>

<template>
  <div class="page-header">
    <h1>{{ title }}</h1>
    <p>{{ description }}</p>
  </div>
</template>

<style scoped>
.page-header {
  margin-bottom: 2rem;
}

.page-header h1 {
  font-size: 1.75rem;
  font-weight: 700;
  margin-bottom: 0.5rem;
}

.page-header p {
  color: #71717a;
  font-size: 1rem;
}
</style>
