// nuxt-resend-examples/javascript/pages/api-keys.vue
<script setup>
const apiKeys = ref([]);
const newKeyName = ref("");
const permission = ref("full_access");
const renameId = ref("");
const renameName = ref("");
const loading = ref(false);
const success = ref(null);
const error = ref(null);

async function loadApiKeys() {
  loading.value = true;
  error.value = null;

  try {
    const data = await $fetch("/api/api-keys");
    apiKeys.value = data.apiKeys;
    success.value = `Found ${data.apiKeys.length} API key(s)`;
  } catch (err) {
    error.value = err.data?.message || err.message || "Failed to load API keys";
  } finally {
    loading.value = false;
  }
}

async function createApiKey() {
  if (!newKeyName.value) return;

  loading.value = true;
  success.value = null;
  error.value = null;

  try {
    const data = await $fetch("/api/api-keys", {
      method: "POST",
      body: { name: newKeyName.value, permission: permission.value },
    });
    success.value = `API key created: ${data.apiKey?.name} (Token: ${data.apiKey?.token}) — copy this now, it won't be shown again`;
    newKeyName.value = "";
    await loadApiKeys();
  } catch (err) {
    error.value = err.data?.message || err.message || "Failed to create API key";
  } finally {
    loading.value = false;
  }
}

async function renameApiKey() {
  if (!renameId.value || !renameName.value) return;

  loading.value = true;
  success.value = null;
  error.value = null;

  try {
    const data = await $fetch(`/api/api-keys/${renameId.value}`, {
      method: "PATCH",
      body: { name: renameName.value },
    });
    success.value = `API key renamed to: ${data.apiKey?.name}`;
    renameId.value = "";
    renameName.value = "";
    await loadApiKeys();
  } catch (err) {
    error.value = err.data?.message || err.message || "Failed to rename API key";
  } finally {
    loading.value = false;
  }
}

async function deleteApiKey(id) {
  loading.value = true;
  success.value = null;
  error.value = null;

  try {
    await $fetch(`/api/api-keys/${id}`, { method: "DELETE" });
    success.value = "API key deleted";
    await loadApiKeys();
  } catch (err) {
    error.value = err.data?.message || err.message || "Failed to delete API key";
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div>
    <PageHeader
      title="API Keys"
      description="Manage API keys with Resend."
    />

    <div class="section">
      <h3>List API Keys</h3>
      <button :disabled="loading" @click="loadApiKeys">
        {{ loading ? "Loading..." : "Load API Keys" }}
      </button>
    </div>

    <div v-if="apiKeys.length > 0" class="api-keys-list">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Created</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="apiKey in apiKeys" :key="apiKey.id">
            <td>{{ apiKey.name }}</td>
            <td>{{ apiKey.created_at }}</td>
            <td class="actions-cell">
              <button type="button" class="secondary" @click="renameId = apiKey.id">
                Rename
              </button>
              <button
                type="button"
                class="danger"
                :disabled="loading"
                @click="deleteApiKey(apiKey.id)"
              >
                Delete
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <form class="form" @submit.prevent="createApiKey">
      <h3>Create API Key</h3>
      <div class="field">
        <label for="key-name">Name</label>
        <input id="key-name" v-model="newKeyName" type="text" placeholder="My API Key" required />
      </div>
      <div class="field">
        <label for="permission">Permission</label>
        <select id="permission" v-model="permission">
          <option value="full_access">full_access</option>
          <option value="sending_access">sending_access</option>
        </select>
      </div>
      <button type="submit" :disabled="loading">
        {{ loading ? "Creating..." : "Create API Key" }}
      </button>
    </form>

    <form class="form" @submit.prevent="renameApiKey">
      <h3>Rename API Key</h3>
      <div class="field">
        <label for="rename-id">API Key ID</label>
        <input id="rename-id" v-model="renameId" type="text" placeholder="API key ID" required />
      </div>
      <div class="field">
        <label for="rename-name">New Name</label>
        <input id="rename-name" v-model="renameName" type="text" placeholder="New name" required />
      </div>
      <button type="submit" :disabled="loading">
        {{ loading ? "Renaming..." : "Rename API Key" }}
      </button>
    </form>

    <ResultDisplay :loading="loading" :success="success" :error="error" />

    <div class="code-example">
      <h3>Code Example</h3>
      <pre><code>// server/api/api-keys/index.get.js
const { data, error } = await resend.apiKeys.list();
return { apiKeys: data?.data || [] };

// server/api/api-keys/index.post.js
const { data, error } = await resend.apiKeys.create({
  name: "My API Key",
  permission: "full_access",
});

// server/api/api-keys/[id].patch.js
const { data, error } = await resend.apiKeys.update(id, { name: "New Name" });

// server/api/api-keys/[id].delete.js
const { data, error } = await resend.apiKeys.remove(id);</code></pre>
    </div>
  </div>
</template>

<style scoped>
.section {
  margin-bottom: 1.5rem;
}

.section h3 {
  font-size: 1rem;
  margin-bottom: 0.75rem;
}

.form {
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  margin-top: 1.5rem;
}

.form h3 {
  font-size: 1rem;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.field label {
  font-size: 0.875rem;
  font-weight: 500;
}

.field input,
.field select {
  padding: 0.5rem 0.75rem;
  border: 1px solid #d4d4d8;
  border-radius: 6px;
  font-size: 0.875rem;
}

button {
  padding: 0.625rem 1.25rem;
  background: #18181b;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  align-self: flex-start;
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

button.secondary {
  background: #f4f4f5;
  color: #18181b;
  border: 1px solid #d4d4d8;
}

button.danger {
  background: #dc2626;
  color: #fff;
}

.api-keys-list {
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 1.5rem;
}

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}

th,
td {
  text-align: left;
  padding: 0.5rem 0.75rem;
  border-bottom: 1px solid #e4e4e7;
}

th {
  font-weight: 600;
  background: #f4f4f5;
}

.actions-cell {
  display: flex;
  gap: 0.5rem;
}

.actions-cell button {
  padding: 0.375rem 0.75rem;
  align-self: auto;
}

.code-example {
  margin-top: 2rem;
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
}

.code-example h3 {
  font-size: 1rem;
  margin-bottom: 1rem;
}

.code-example pre {
  background: #f4f4f5;
  padding: 1rem;
  border-radius: 6px;
  overflow-x: auto;
  font-size: 0.8rem;
  line-height: 1.5;
}
</style>

// sveltekit-resend-examples/javascript/src/routes/api-keys/+page.svelte
<script>
  import PageHeader from "$lib/components/PageHeader.svelte";
  import ResultDisplay from "$lib/components/ResultDisplay.svelte";

  let apiKeys = $state([]);
  let loadingKeys = $state(false);
  let loading = $state(false);
  let error = $state(null);
  let success = $state(null);
  let data = $state(null);

  async function loadApiKeys() {
    loadingKeys = true;
    error = null;

    try {
      const response = await fetch("/api/api-keys");
      const result = await response.json();

      if (!response.ok) {
        error = result.error || "Failed to load API keys";
        return;
      }

      apiKeys = result.data || [];
    } catch (err) {
      error = err instanceof Error ? err.message : "An error occurred";
    } finally {
      loadingKeys = false;
    }
  }

  let name = $state("");
  let permission = $state("full_access");
  let domainId = $state("");

  async function createApiKey() {
    loading = true;
    error = null;
    success = null;
    data = null;

    try {
      const response = await fetch("/api/api-keys", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name,
          permission,
          domainId: permission === "sending_access" ? domainId : undefined,
        }),
      });

      const result = await response.json();

      if (!response.ok) {
        error = result.error || "Failed to create API key";
        return;
      }

      success = "API key created! Copy the token now — it won't be shown again.";
      data = result;
      name = "";
      domainId = "";
      await loadApiKeys();
    } catch (err) {
      error = err instanceof Error ? err.message : "An error occurred";
    } finally {
      loading = false;
    }
  }

  let renamingId = $state(null);
  let renameValue = $state("");
  let renaming = $state(false);

  function startRename(key) {
    renamingId = key.id;
    renameValue = key.name;
  }

  function cancelRename() {
    renamingId = null;
    renameValue = "";
  }

  async function renameApiKey(id) {
    renaming = true;
    error = null;
    success = null;
    data = null;

    try {
      const response = await fetch("/api/api-keys", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, name: renameValue }),
      });

      const result = await response.json();

      if (!response.ok) {
        error = result.error || "Failed to rename API key";
        return;
      }

      success = "API key renamed successfully!";
      data = result;
      renamingId = null;
      renameValue = "";
      await loadApiKeys();
    } catch (err) {
      error = err instanceof Error ? err.message : "An error occurred";
    } finally {
      renaming = false;
    }
  }

  let deletingId = $state(null);

  async function deleteApiKey(id) {
    deletingId = id;
    error = null;
    success = null;
    data = null;

    try {
      const response = await fetch("/api/api-keys", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });

      const result = await response.json();

      if (!response.ok) {
        error = result.error || "Failed to delete API key";
        return;
      }

      success = "API key deleted successfully!";
      data = result;
      await loadApiKeys();
    } catch (err) {
      error = err instanceof Error ? err.message : "An error occurred";
    } finally {
      deletingId = null;
    }
  }
</script>

<PageHeader
  title="API Keys"
  description="Create, list, rename, and delete API keys."
/>

<div class="sections">
  <section>
    <h2>Create API Key</h2>
    <form onsubmit={createApiKey} class="form">
      <div class="field">
        <label for="name">Name</label>
        <input id="name" type="text" bind:value={name} placeholder="Production Sending Key" required />
      </div>

      <div class="field">
        <label for="permission">Permission</label>
        <select id="permission" bind:value={permission}>
          <option value="full_access">Full access</option>
          <option value="sending_access">Sending access</option>
        </select>
      </div>

      {#if permission === "sending_access"}
        <div class="field">
          <label for="domainId">Domain ID (optional)</label>
          <input id="domainId" type="text" bind:value={domainId} placeholder="Restrict to a single domain" />
        </div>
      {/if}

      <button type="submit" disabled={loading}>
        {loading ? "Creating..." : "Create Key"}
      </button>
    </form>
  </section>

  <section>
    <h2>API Keys</h2>
    <button class="secondary" onclick={loadApiKeys} disabled={loadingKeys}>
      {loadingKeys ? "Loading..." : "Load API Keys"}
    </button>

    {#if apiKeys.length > 0}
      <ul class="key-list">
        {#each apiKeys as key (key.id)}
          <li class="key-row">
            {#if renamingId === key.id}
              <input type="text" bind:value={renameValue} class="rename-input" />
              <button onclick={() => renameApiKey(key.id)} disabled={renaming}>
                {renaming ? "Saving..." : "Save"}
              </button>
              <button class="secondary" onclick={cancelRename} disabled={renaming}>
                Cancel
              </button>
            {:else}
              <span class="key-name">{key.name}</span>
              <button class="secondary" onclick={() => startRename(key)}>
                Rename
              </button>
              <button class="danger" onclick={() => deleteApiKey(key.id)} disabled={deletingId === key.id}>
                {deletingId === key.id ? "Deleting..." : "Delete"}
              </button>
            {/if}
          </li>
        {/each}
      </ul>
    {/if}
  </section>
</div>

<ResultDisplay {loading} {error} {success} {data} />

<details class="code-example">
  <summary>View example code</summary>
  <pre><code>{`// src/routes/api/api-keys/+server.js
import { json } from '@sveltejs/kit';
import { resend } from '$lib/server/resend';

export async function GET() {
  const { data, error } = await resend.apiKeys.list();

  if (error) {
    return json({ error: error.message }, { status: 400 });
  }

  return json(data);
}

export async function POST({ request }) {
  const { name, permission, domainId } = await request.json();

  const { data, error } = await resend.apiKeys.create({
    name,
    permission,
    domainId,
  });

  if (error) {
    return json({ error: error.message }, { status: 400 });
  }

  return json(data);
}

export async function PATCH({ request }) {
  const { id, name } = await request.json();

  // Only \`name\` is patchable — a leaked key must not be able to
  // widen another key's scope via permission or domainId.
  const { data, error } = await resend.apiKeys.update(id, { name });

  if (error) {
    return json({ error: error.message }, { status: 400 });
  }

  return json(data);
}

export async function DELETE({ request }) {
  const { id } = await request.json();

  const { data, error } = await resend.apiKeys.remove(id);

  if (error) {
    return json({ error: error.message }, { status: 400 });
  }

  return json(data);
}`}</code></pre>
</details>

<style>
  .sections {
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }

  section h2 {
    font-size: 1.25rem;
    font-weight: 600;
    margin: 0 0 1rem;
    color: #111827;
  }

  .form {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    max-width: 32rem;
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }

  label {
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
  }

  input,
  select {
    padding: 0.5rem 0.75rem;
    border: 1px solid #d1d5db;
    border-radius: 0.375rem;
    font-size: 0.875rem;
  }

  input:focus,
  select:focus {
    outline: none;
    border-color: #6366f1;
    box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
  }

  button {
    align-self: flex-start;
    padding: 0.5rem 1.25rem;
    background-color: #6366f1;
    color: #ffffff;
    border: none;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
  }

  button:hover:not(:disabled) {
    background-color: #4f46e5;
  }

  button:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .secondary {
    background-color: #ffffff;
    color: #374151;
    border: 1px solid #d1d5db;
  }

  .secondary:hover:not(:disabled) {
    background-color: #f9fafb;
  }

  .danger {
    background-color: #ffffff;
    color: #dc2626;
    border: 1px solid #fca5a5;
  }

  .danger:hover:not(:disabled) {
    background-color: #fef2f2;
  }

  .key-list {
    list-style: none;
    margin: 1rem 0 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .key-row {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.75rem 1rem;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
  }

  .key-name {
    flex: 1;
    font-size: 0.875rem;
    color: #111827;
    font-weight: 500;
    word-break: break-all;
  }

  .rename-input {
    flex: 1;
  }

  .key-row button {
    align-self: auto;
  }

  .code-example {
    margin-top: 2rem;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
    overflow: hidden;
  }

  summary {
    padding: 0.75rem 1rem;
    background: #f9fafb;
    cursor: pointer;
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
  }

  .code-example pre {
    margin: 0;
    padding: 1rem;
    background: #1f2937;
    color: #e5e7eb;
    font-size: 0.8rem;
    overflow-x: auto;
  }
</style>
