// nuxt-resend-examples/javascript/pages/scheduling.vue
<script setup>
const to = ref("delivered@resend.dev");
const subject = ref("Scheduled Email");
const message = ref("This email was scheduled for later delivery.");
const delayMinutes = ref(5);
const loading = ref(false);
const success = ref(null);
const error = ref(null);

async function sendEmail() {
  loading.value = true;
  success.value = null;
  error.value = null;

  const scheduledAt = new Date(
    Date.now() + delayMinutes.value * 60 * 1000
  ).toISOString();

  try {
    const data = await $fetch("/api/send-scheduled", {
      method: "POST",
      body: {
        to: to.value,
        subject: subject.value,
        message: message.value,
        scheduledAt,
      },
    });
    success.value = `Email scheduled successfully!\nEmail ID: ${data.id}\nScheduled for: ${data.scheduledAt}`;
  } catch (err) {
    error.value = err.data?.message || err.message || "Failed to schedule email";
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div>
    <PageHeader
      title="Scheduling"
      description="Schedule an email for later delivery. Maximum scheduling window: 7 days."
    />

    <form class="form" @submit.prevent="sendEmail">
      <div class="field">
        <label for="to">To</label>
        <input id="to" v-model="to" type="email" required />
      </div>
      <div class="field">
        <label for="subject">Subject</label>
        <input id="subject" v-model="subject" type="text" required />
      </div>
      <div class="field">
        <label for="message">Message</label>
        <textarea id="message" v-model="message" rows="3" required />
      </div>
      <div class="field">
        <label for="delay">Delay (minutes)</label>
        <input id="delay" v-model.number="delayMinutes" type="number" min="1" max="10080" required />
      </div>
      <button type="submit" :disabled="loading">
        {{ loading ? "Scheduling..." : "Schedule Email" }}
      </button>
    </form>

    <ResultDisplay :loading="loading" :success="success" :error="error" />

    <div class="code-example">
      <h3>Code Example</h3>
      <pre><code>// server/api/send-scheduled.post.js
const scheduledAt = new Date(
  Date.now() + 5 * 60 * 1000
).toISOString();

const { data, error } = await resend.emails.send({
  from: config.emailFrom,
  to: [to],
  subject,
  html: "&lt;p&gt;Hello from the future!&lt;/p&gt;",
  scheduledAt,
});

// To cancel: resend.emails.cancel(data.id)</code></pre>
    </div>
  </div>
</template>

<style scoped>
.form {
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.field label {
  font-size: 0.875rem;
  font-weight: 500;
}

.field input,
.field textarea {
  padding: 0.5rem 0.75rem;
  border: 1px solid #d4d4d8;
  border-radius: 6px;
  font-size: 0.875rem;
}

button {
  padding: 0.625rem 1.25rem;
  background: #18181b;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  align-self: flex-start;
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.code-example {
  margin-top: 2rem;
  background: #fff;
  border: 1px solid #e4e4e7;
  border-radius: 8px;
  padding: 1.5rem;
}

.code-example h3 {
  font-size: 1rem;
  margin-bottom: 1rem;
}

.code-example pre {
  background: #f4f4f5;
  padding: 1rem;
  border-radius: 6px;
  overflow-x: auto;
  font-size: 0.8rem;
  line-height: 1.5;
}
</style>

// remix-resend-examples/javascript/app/routes/scheduling.jsx
import { useFetcher } from "@remix-run/react";
import { json } from "@remix-run/node";
import { Resend } from "resend";
import { PageHeader } from "~/components/PageHeader";
import { ResultDisplay } from "~/components/ResultDisplay";

const resend = new Resend(process.env.RESEND_API_KEY);

export const meta = () => {
  return [{ title: "Scheduled Send - Remix + Resend" }];
};

export async function action({ request }) {
  const formData = await request.formData();
  const to = formData.get("to");
  const subject = formData.get("subject");
  const message = formData.get("message");
  const minutes = formData.get("minutes");

  if (!to || !subject || !message) {
    return json(
      { error: "Missing required fields: to, subject, message" },
      { status: 400 }
    );
  }

  const from = process.env.EMAIL_FROM || "Acme <onboarding@resend.dev>";

  const delay = Math.min(Number(minutes) || 5, 10080);
  const scheduledAt = new Date(Date.now() + delay * 60 * 1000).toISOString();

  const { data, error } = await resend.emails.send({
    from,
    to: [to],
    subject,
    html: `<h1>Hello from the future!</h1><p>${message}</p>`,
    scheduledAt,
  });

  if (error) {
    return json({ error: error.message }, { status: 500 });
  }

  return json({ success: true, id: data?.id, scheduledAt });
}

export default function Scheduling() {
  const fetcher = useFetcher();

  return (
    <div>
      <PageHeader
        title="Scheduled Send"
        description="Schedule an email for future delivery. Maximum scheduling window is 7 days."
      />

      <fetcher.Form method="post" style={{ display: "grid", gap: "16px" }}>
        <div>
          <label htmlFor="to" style={labelStyle}>
            To
          </label>
          <input
            id="to"
            name="to"
            type="email"
            placeholder="delivered@resend.dev"
            required
            style={inputStyle}
          />
        </div>
        <div>
          <label htmlFor="subject" style={labelStyle}>
            Subject
          </label>
          <input
            id="subject"
            name="subject"
            defaultValue="Scheduled Email"
            required
            style={inputStyle}
          />
        </div>
        <div>
          <label htmlFor="message" style={labelStyle}>
            Message
          </label>
          <textarea
            id="message"
            name="message"
            defaultValue="This email was scheduled for later delivery."
            required
            rows={3}
            style={inputStyle}
          />
        </div>
        <div>
          <label htmlFor="minutes" style={labelStyle}>
            Delay (minutes)
          </label>
          <input
            id="minutes"
            name="minutes"
            type="number"
            defaultValue="5"
            min="1"
            max="10080"
            required
            style={inputStyle}
          />
        </div>
        <button type="submit" style={buttonStyle}>
          {fetcher.state === "submitting" ? "Scheduling..." : "Schedule Email"}
        </button>
      </fetcher.Form>

      <ResultDisplay state={fetcher.state} data={fetcher.data} />

      <div style={codeBlockStyle}>
        <h3 style={{ margin: "0 0 12px 0", fontSize: "14px" }}>API Code</h3>
        <pre style={preStyle}>{`const scheduledAt = new Date(
  Date.now() + 5 * 60 * 1000
).toISOString();

const { data, error } = await resend.emails.send({
  from: "Acme <onboarding@resend.dev>",
  to: ["delivered@resend.dev"],
  subject: "Scheduled Email",
  html: "<h1>Hello from the future!</h1>",
  scheduledAt,
});

// To cancel: resend.emails.cancel(data.id)`}</pre>
      </div>
    </div>
  );
}

const labelStyle = {
  display: "block",
  marginBottom: "4px",
  fontSize: "14px",
  fontWeight: 500,
};

const inputStyle = {
  width: "100%",
  padding: "8px 12px",
  border: "1px solid #d4d4d8",
  borderRadius: "6px",
  fontSize: "14px",
  boxSizing: "border-box",
};

const buttonStyle = {
  padding: "10px 20px",
  backgroundColor: "#18181b",
  color: "#fff",
  border: "none",
  borderRadius: "6px",
  fontSize: "14px",
  fontWeight: 500,
  cursor: "pointer",
};

const codeBlockStyle = {
  marginTop: "32px",
  padding: "20px",
  backgroundColor: "#18181b",
  borderRadius: "8px",
  color: "#e4e4e7",
};

const preStyle = {
  margin: 0,
  fontSize: "13px",
  whiteSpace: "pre-wrap",
  wordBreak: "break-all",
};
