// sveltekit-resend-examples/typescript/src/routes/segments/+page.svelte
<script lang="ts">
  import PageHeader from "$lib/components/PageHeader.svelte";
  import ResultDisplay from "$lib/components/ResultDisplay.svelte";

  let contacts = $state<unknown[]>([]);
  let loadingContacts = $state(false);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let success = $state<string | null>(null);
  let data = $state<unknown>(null);

  async function loadContacts() {
    loadingContacts = true;
    error = null;

    try {
      const response = await fetch("/api/segments/contacts");
      const result = await response.json();

      if (!response.ok) {
        error = result.error || "Failed to load contacts";
        return;
      }

      contacts = result.data || [];
    } catch (err) {
      error = err instanceof Error ? err.message : "An error occurred";
    } finally {
      loadingContacts = false;
    }
  }

  let email = $state("");
  let firstName = $state("");
  let lastName = $state("");

  async function addContact() {
    loading = true;
    error = null;
    success = null;
    data = null;

    try {
      const response = await fetch("/api/segments/contacts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, firstName, lastName }),
      });

      const result = await response.json();

      if (!response.ok) {
        error = result.error || "Failed to add contact";
        return;
      }

      success = "Contact added successfully!";
      data = result;
      email = "";
      firstName = "";
      lastName = "";
      await loadContacts();
    } catch (err) {
      error = err instanceof Error ? err.message : "An error occurred";
    } finally {
      loading = false;
    }
  }
</script>

<PageHeader
  title="Segments"
  description="Manage contacts and segments with the Resend API."
/>

<div class="sections">
  <section>
    <h2>Add Contact</h2>
    <form onsubmit={addContact} class="form">
      <div class="field">
        <label for="email">Email</label>
        <input id="email" type="email" bind:value={email} placeholder="contact@example.com" required />
      </div>

      <div class="field">
        <label for="firstName">First Name</label>
        <input id="firstName" type="text" bind:value={firstName} placeholder="John" />
      </div>

      <div class="field">
        <label for="lastName">Last Name</label>
        <input id="lastName" type="text" bind:value={lastName} placeholder="Doe" />
      </div>

      <button type="submit" disabled={loading}>
        {loading ? "Adding..." : "Add Contact"}
      </button>
    </form>
  </section>

  <section>
    <h2>Contacts</h2>
    <button class="secondary" onclick={loadContacts} disabled={loadingContacts}>
      {loadingContacts ? "Loading..." : "Load Contacts"}
    </button>

    {#if contacts.length > 0}
      <ul class="contact-list">
        {#each contacts as contact}
          <li>{JSON.stringify(contact)}</li>
        {/each}
      </ul>
    {/if}
  </section>
</div>

<ResultDisplay {loading} {error} {success} {data} />

<details class="code-example">
  <summary>View example code</summary>
  <pre><code>{`// src/routes/api/segments/contacts/+server.ts
import { json } from '@sveltejs/kit';
import { resend } from '$lib/server/resend';
import { RESEND_SEGMENT_ID } from '$env/static/private';
import type { RequestHandler } from './$types';

export const GET: RequestHandler = async () => {
  const { data, error } = await resend.contacts.list({
    segmentId: RESEND_SEGMENT_ID,
  });

  if (error) {
    return json({ error: error.message }, { status: 400 });
  }

  return json(data);
};

export const POST: RequestHandler = async ({ request }) => {
  const { email, firstName, lastName } = await request.json();

  const { data, error } = await resend.contacts.create({
    email,
    firstName,
    lastName,
    segments: [{ id: RESEND_SEGMENT_ID }],
  });

  if (error) {
    return json({ error: error.message }, { status: 400 });
  }

  return json(data);
};`}</code></pre>
</details>

<style>
  .sections {
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }

  section h2 {
    font-size: 1.25rem;
    font-weight: 600;
    margin: 0 0 1rem;
    color: #111827;
  }

  .form {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    max-width: 32rem;
  }

  .field {
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }

  label {
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
  }

  input {
    padding: 0.5rem 0.75rem;
    border: 1px solid #d1d5db;
    border-radius: 0.375rem;
    font-size: 0.875rem;
  }

  input:focus {
    outline: none;
    border-color: #6366f1;
    box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
  }

  button {
    align-self: flex-start;
    padding: 0.5rem 1.25rem;
    background-color: #6366f1;
    color: #ffffff;
    border: none;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
  }

  button:hover:not(:disabled) {
    background-color: #4f46e5;
  }

  button:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .secondary {
    background-color: #ffffff;
    color: #374151;
    border: 1px solid #d1d5db;
  }

  .secondary:hover:not(:disabled) {
    background-color: #f9fafb;
  }

  .contact-list {
    margin-top: 1rem;
    padding-left: 1.25rem;
    font-size: 0.875rem;
    color: #374151;
  }

  .contact-list li {
    margin-bottom: 0.5rem;
    word-break: break-all;
  }

  .code-example {
    margin-top: 2rem;
    border: 1px solid #e5e7eb;
    border-radius: 0.5rem;
    overflow: hidden;
  }

  summary {
    padding: 0.75rem 1rem;
    background: #f9fafb;
    cursor: pointer;
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
  }

  pre {
    margin: 0;
    padding: 1rem;
    background: #1f2937;
    color: #e5e7eb;
    font-size: 0.8rem;
    overflow-x: auto;
  }
</style>

// remix-resend-examples/javascript/app/routes/segments.jsx
import { useFetcher, useLoaderData } from "@remix-run/react";
import { json } from "@remix-run/node";
import { Resend } from "resend";
import { PageHeader } from "~/components/PageHeader";
import { ResultDisplay } from "~/components/ResultDisplay";

const resend = new Resend(process.env.RESEND_API_KEY);

export const meta = () => {
  return [{ title: "Segments - Remix + Resend" }];
};

export async function loader() {
  const segmentId = process.env.RESEND_SEGMENT_ID;

  if (!segmentId) {
    return json({ contacts: [], error: "RESEND_SEGMENT_ID not configured" });
  }

  const { data: segments } = await resend.segments.list();
  const { data: contacts } = await resend.contacts.list({ segmentId });

  return json({
    segments: segments?.data || [],
    contacts: contacts?.data || [],
  });
}

export async function action({ request }) {
  const formData = await request.formData();
  const intent = formData.get("intent");

  const segmentId = process.env.RESEND_SEGMENT_ID;
  if (!segmentId) {
    return json({ error: "RESEND_SEGMENT_ID not configured" }, { status: 500 });
  }

  if (intent === "create") {
    const email = formData.get("email");
    const firstName = formData.get("firstName");
    const lastName = formData.get("lastName");

    if (!email) {
      return json({ error: "Missing required field: email" }, { status: 400 });
    }

    const { data, error } = await resend.contacts.create({
      email,
      firstName: firstName || undefined,
      lastName: lastName || undefined,
      unsubscribed: false,
      segments: [{ id: segmentId }],
    });

    if (error) {
      return json({ error: error.message }, { status: 500 });
    }

    return json({ success: true, contact: data });
  }

  if (intent === "remove") {
    const contactId = formData.get("contactId");

    if (!contactId) {
      return json({ error: "Missing required field: contactId" }, { status: 400 });
    }

    const { error } = await resend.contacts.remove({
      id: contactId,
    });

    if (error) {
      return json({ error: error.message }, { status: 500 });
    }

    return json({ success: true, removed: contactId });
  }

  return json({ error: "Unknown intent" }, { status: 400 });
}

export default function Segments() {
  const loaderData = useLoaderData();
  const fetcher = useFetcher();

  return (
    <div>
      <PageHeader
        title="Segments"
        description="Manage segments and contacts. Set RESEND_SEGMENT_ID in your .env file."
      />

      <div style={{ marginBottom: "32px" }}>
        <h2 style={{ fontSize: "20px", marginBottom: "12px" }}>Contacts</h2>
        {loaderData.contacts && loaderData.contacts.length > 0 ? (
          <ul style={{ listStyle: "none", padding: 0 }}>
            {loaderData.contacts.map((contact) => (
              <li
                key={contact.id}
                style={{
                  padding: "12px",
                  backgroundColor: "#fff",
                  border: "1px solid #e4e4e7",
                  borderRadius: "6px",
                  marginBottom: "8px",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <span>
                  {contact.first_name} {contact.last_name} &lt;{contact.email}&gt;
                  {contact.unsubscribed && (
                    <span style={{ color: "#dc2626", marginLeft: "8px", fontSize: "12px" }}>
                      (unsubscribed)
                    </span>
                  )}
                </span>
                <fetcher.Form method="post" style={{ display: "inline" }}>
                  <input type="hidden" name="intent" value="remove" />
                  <input type="hidden" name="contactId" value={contact.id} />
                  <button
                    type="submit"
                    style={{
                      padding: "4px 12px",
                      backgroundColor: "#fef2f2",
                      color: "#dc2626",
                      border: "1px solid #fecaca",
                      borderRadius: "4px",
                      cursor: "pointer",
                      fontSize: "12px",
                    }}
                  >
                    Remove
                  </button>
                </fetcher.Form>
              </li>
            ))}
          </ul>
        ) : (
          <p style={{ color: "#71717a" }}>No contacts found.</p>
        )}
      </div>

      <h2 style={{ fontSize: "20px", marginBottom: "12px" }}>Add Contact</h2>
      <fetcher.Form method="post" style={{ display: "grid", gap: "16px" }}>
        <input type="hidden" name="intent" value="create" />
        <div>
          <label htmlFor="email" style={labelStyle}>
            Email
          </label>
          <input
            id="email"
            name="email"
            type="email"
            placeholder="jane@example.com"
            required
            style={inputStyle}
          />
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
          <div>
            <label htmlFor="firstName" style={labelStyle}>
              First Name
            </label>
            <input id="firstName" name="firstName" placeholder="Jane" style={inputStyle} />
          </div>
          <div>
            <label htmlFor="lastName" style={labelStyle}>
              Last Name
            </label>
            <input id="lastName" name="lastName" placeholder="Doe" style={inputStyle} />
          </div>
        </div>
        <button type="submit" style={buttonStyle}>
          {fetcher.state === "submitting" ? "Adding..." : "Add Contact"}
        </button>
      </fetcher.Form>

      <ResultDisplay state={fetcher.state} data={fetcher.data} />

      <div style={codeBlockStyle}>
        <h3 style={{ margin: "0 0 12px 0", fontSize: "14px" }}>API Code</h3>
        <pre style={preStyle}>{`// Create a contact
const { data, error } = await resend.contacts.create({
  email: "jane@example.com",
  firstName: "Jane",
  lastName: "Doe",
  unsubscribed: false,
  segments: [{ id: "seg_..." }],
});

// List contacts
const { data: contacts } = await resend.contacts.list({
  segmentId: "seg_...",
});

// Remove a contact
await resend.contacts.remove({
  id: contact.id,
});`}</pre>
      </div>
    </div>
  );
}

const labelStyle = {
  display: "block",
  marginBottom: "4px",
  fontSize: "14px",
  fontWeight: 500,
};

const inputStyle = {
  width: "100%",
  padding: "8px 12px",
  border: "1px solid #d4d4d8",
  borderRadius: "6px",
  fontSize: "14px",
  boxSizing: "border-box",
};

const buttonStyle = {
  padding: "10px 20px",
  backgroundColor: "#18181b",
  color: "#fff",
  border: "none",
  borderRadius: "6px",
  fontSize: "14px",
  fontWeight: 500,
  cursor: "pointer",
};

const codeBlockStyle = {
  marginTop: "32px",
  padding: "20px",
  backgroundColor: "#18181b",
  borderRadius: "8px",
  color: "#e4e4e7",
};

const preStyle = {
  margin: 0,
  fontSize: "13px",
  whiteSpace: "pre-wrap",
  wordBreak: "break-all",
};
